

library (tree)
Carseats <- read.csv("C:/Users/atluria/Desktop/teachings/decision_tree_7thApril/Carseats.csv")

View(Carseats)

#Creating separte Data set of Sales here

Sales<-Carseats$Sales

#As Sales is a NOminal variable it sometimes won't fit into the view table, 
#so need to use the Data frame syntax to read the same

Sales<-data.frame(Sales)
View(Sales)

tree.carseats<-tree(Sales~. ,Carseats)

summary (tree.carseats )
plot(tree.carseats)   # plotting the sturcture of the tree

text(tree.carseats,pretty =0) # giving text to the tree
tree.carseats #Looking at all the rules generated by the tree method (27 in this case)



set.seed (2) #Randomizing the data
train=sample (1: nrow(Carseats ), 200)  # Creating a Training Data for CarSales 50%
Carseats.test=Carseats [-train ,] # Creating the test data 50%

set.seed (2) #Randomizing the data 
Sales.train=sample (1: nrow(Sales), 200) # Creatign the training data for the SAles
Sales.test=Sales[-train ] # Creating the testing data for the Sales variable



# Based on created 27 rules predicting Training Data

tree.carseats =tree(Sales~. ,Carseats ,subset =train ) 

# Applying the rules created from Training on the Testing 

tree.pred=predict(tree.carseats ,Carseats.test ,type ="class") 

# Confusion matrix from both Training and Testing

table(tree.pred,Sales.test) 


set.seed (3)

# Cross validating my results on the full data for their classifcation

cv.carseats =cv.tree(tree.carseats ,FUN=prune.misclass ) #FUN The function to do the pruning.

names(cv.carseats)
par(mfrow =c(1,2))

# Type = character string. If this partially matches "uniform", 
# the branches are of uniform length. 
# Otherwise they are proportional to the decrease in impurity

plot(cv.carseats$size ,cv.carseats$dev ,type="b")

# K The number of folds of the cross-validation.

plot(cv.carseats$k ,cv.carseats$dev ,type="b")

# best = integer requesting the size 

prune.carseats =prune.misclass (tree.carseats ,best =9)

plot(prune.carseats )

text(prune.carseats ,pretty =0)

tree.pred=predict (prune.carseats,Carseats.test,type="class")
table(tree.pred ,Sales.test)

prune.carseats =prune.misclass (tree.carseats ,best =15)
plot(prune.carseats )
text(prune.carseats ,pretty =0)
tree.pred=predict (prune.carseats,Carseats.test,type="class")
table(tree.pred ,Sales.test)

